// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pwdmgr.Infrastructure.Persistence;

#nullable disable

namespace Pwdmgr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PwdmgrDbContext))]
    [Migration("20260915134643_IntegrityConstraints")]
    partial class IntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pwdmgr.Domain.Crypto.UserKeyring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_private_key");

                    b.Property<string>("KdfAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kdf_algorithm");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_iterations");

                    b.Property<int>("KdfMemoryKib")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_memory_kib");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_parallelism");

                    b.Property<byte[]>("KdfSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea")
                        .HasColumnName("kdf_salt");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_keyrings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_keyrings_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_keyrings_tenant_id_user_id");

                    b.ToTable("user_keyrings", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_keyrings_kdf_range", "kdf_memory_kib BETWEEN 19456 AND 1048576 AND kdf_iterations BETWEEN 2 AND 16 AND kdf_parallelism BETWEEN 1 AND 16");

                            t.HasCheckConstraint("ck_user_keyrings_kdf_salt_len", "octet_length(kdf_salt) BETWEEN 16 AND 64");

                            t.HasCheckConstraint("ck_user_keyrings_private_key_len", "octet_length(encrypted_private_key) BETWEEN 28 AND 4096");

                            t.HasCheckConstraint("ck_user_keyrings_public_key_len", "octet_length(public_key) = 32");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Crypto.WrappedKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_type");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wrapped_keys");

                    b.HasIndex("TenantId", "RecipientId")
                        .HasDatabaseName("ix_wrapped_keys_tenant_id_recipient_id");

                    b.HasIndex("TenantId", "ResourceId")
                        .HasDatabaseName("ix_wrapped_keys_tenant_id_resource_id");

                    b.HasIndex("TenantId", "RecipientType", "RecipientId")
                        .HasDatabaseName("ix_wrapped_keys_tenant_id_recipient_type_recipient_id");

                    b.HasIndex("TenantId", "ResourceType", "ResourceId", "RecipientType", "RecipientId", "KeyVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_wrapped_keys_resource_recipient_version");

                    b.ToTable("wrapped_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_wrapped_keys_ciphertext_len", "octet_length(ciphertext) BETWEEN 60 AND 1024");

                            t.HasCheckConstraint("ck_wrapped_keys_types", "resource_type = 1 AND recipient_type = 1");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Identity.LocalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PepperVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pepper_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_local_credentials");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_local_credentials_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_local_credentials_tenant_id_user_id");

                    b.ToTable("local_credentials", (string)null);
                });

            modelBuilder.Entity("Pwdmgr.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_users_tenant_id_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.HasIndex("TenantId", "Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_source_external_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pwdmgr.Domain.Secrets.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LatestVersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version_no");

                    b.Property<byte[]>("NameCiphertext")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("name_ciphertext");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_secrets");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_secrets_tenant_id_id");

                    b.HasIndex("TenantId", "VaultId", "Status")
                        .HasDatabaseName("ix_secrets_tenant_id_vault_id_status");

                    b.ToTable("secrets", null, t =>
                        {
                            t.HasCheckConstraint("ck_secrets_name_len", "octet_length(name_ciphertext) BETWEEN 28 AND 1024");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Secrets.SecretVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AadHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("aad_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.Property<byte[]>("PayloadCiphertext")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("bytea")
                        .HasColumnName("payload_ciphertext");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("Id")
                        .HasName("pk_secret_versions");

                    b.HasIndex("TenantId", "SecretId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_secret_versions_tenant_id_secret_id_version_no");

                    b.ToTable("secret_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_secret_versions_aad_hash_len", "octet_length(aad_hash) = 32");

                            t.HasCheckConstraint("ck_secret_versions_payload_len", "octet_length(payload_ciphertext) BETWEEN 28 AND 65536");

                            t.HasCheckConstraint("ck_secret_versions_version_no", "version_no >= 1");

                            t.HasCheckConstraint("ck_secret_versions_wrapped_dek_len", "octet_length(wrapped_dek) BETWEEN 60 AND 256");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_sessions_revoked_at")
                        .HasFilter("revoked_at IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_token_hash");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_sessions_tenant_id_user_id");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_token_hash_len", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Pwdmgr.Domain.Vaults.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<byte[]>("NameCiphertext")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("name_ciphertext");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vaults");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_vaults_tenant_id_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_vaults_tenant_id_status");

                    b.ToTable("vaults", null, t =>
                        {
                            t.HasCheckConstraint("ck_vaults_name_len", "octet_length(name_ciphertext) BETWEEN 28 AND 1024");
                        });
                });

            modelBuilder.Entity("Pwdmgr.Domain.Crypto.UserKeyring", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_keyrings_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("Pwdmgr.Domain.Crypto.UserKeyring", "TenantId", "UserId")
                        .HasPrincipalKey("Pwdmgr.Domain.Identity.User", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_keyrings_users_tenant_id_user_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Crypto.WrappedKey", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wrapped_keys_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RecipientId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wrapped_keys_users_tenant_id_recipient_id");

                    b.HasOne("Pwdmgr.Domain.Vaults.Vault", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ResourceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wrapped_keys_vaults_tenant_id_resource_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Identity.LocalCredential", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_local_credentials_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("Pwdmgr.Domain.Identity.LocalCredential", "TenantId", "UserId")
                        .HasPrincipalKey("Pwdmgr.Domain.Identity.User", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_local_credentials_users_tenant_id_user_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Identity.User", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Secrets.Secret", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secrets_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Vaults.Vault", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "VaultId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secrets_vaults_tenant_id_vault_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Secrets.SecretVersion", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_versions_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Secrets.Secret", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SecretId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_secret_versions_secrets_tenant_id_secret_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Sessions.Session", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_tenants_tenant_id");

                    b.HasOne("Pwdmgr.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_tenant_id_user_id");
                });

            modelBuilder.Entity("Pwdmgr.Domain.Vaults.Vault", b =>
                {
                    b.HasOne("Pwdmgr.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vaults_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
